name: CI/CD Miel Dorada

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PORT: 3001 

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Backend Tests
        env:
          DB_URL: ${{ secrets.DB_URL }}           # Usa tu secret de MongoDB Atlas
          SECRET_KEY: ${{ secrets.SECRET_KEY }}   # Usa tu secret para JWT
        run: |
          if [ -f "Backend/test/*.test.js" ]; then
            npm test
          else
            echo "⚠️ No hay tests - Continuando..."
          fi

      - name: Build Frontend
        run: |
          cd Frontend
          echo "✅ Frontend estático - No necesita build"
          mkdir -p dist && cp -r *.html css/ js/ imagenes/ dist/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: |
            Backend/
            Frontend/dist/
            package.json